name: yelbebe_button
description: "Dejaron atrapado al bebé?"
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  animate_gradient: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yelbebe.mp3
    - assets/yelbebe.png
